[patch.crates-io]
# Update nix/overlay.nix with the sha256:
# nix-prefetch-url https://github.com/openebs/Mayastor/tarball/$rev --print-path --unpack

[profile.dev]
panic = "abort"

[workspace]
members = [
    "common",
    "composer",
    "control-plane/agents",
    "control-plane/rest",
    "deployer",
    "openapi",
    "rpc",
# Test mayastor through the rest api
    "tests/tests-mayastor",
]
