[package]
name = "rpc"
version = "1.0.0"
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
edition = "2018"

[build-dependencies]
tonic-build = "0.8.0"
prost-build = "0.11.1"

[dependencies]
tonic = "0.8.0"
bytes = "1.2.0"
prost = "0.11.0"
prost-derive = "0.11.0"
prost-types = "0.11.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_derive = "1.0.140"
serde_json = "1.0.82"
strum = "0.21.0"
strum_macros = "0.21.1"
