apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-agents
  namespace: mayastor
  labels:
    app: core-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-agents
  template:
    metadata:
      labels:
        app: core-agents
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
        - name: core
          resources: {{- .Values.core.resources | toYaml | nindent 12 }}
          image: {{ .Values.mayastorCP.registry }}mayadata/mcp-core:{{ .Values.mayastorCP.tag }}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "-smayastor-etcd"
            - "-nnats"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"
            - "--cache-period={{ .Values.base.cache_poll_period }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.mayastorCP.logLevel }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace