apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: mayastor
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
        - name: rest
          resources: {{- .Values.rest.resources | toYaml | nindent 12 }}
          image: {{ .Values.mayastorCP.registry }}mayadata/mcp-rest:{{ .Values.mayastorCP.tag }}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "--dummy-certificates"
            - "--no-auth"
            - "-nnats"
            - "--http=0.0.0.0:8081"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: RUST_LOG
              value: {{ .Values.mayastorCP.logLevel }}
            - name: LLVM_PROFILE_FILE
              value: /var/local/mayastor-coverage/rest.profraw
          volumeMounts:
            - name: coverage
              mountPath: /var/local/mayastor-coverage/
      volumes:
        - name: coverage
          hostPath:
            path: /var/local/mayastor-coverage/
            type: DirectoryOrCreate
