---
# Source: mayastor-control-plane/templates/rest-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: mayastor
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: mayadata/mcp-rest:develop
          imagePullPolicy: Always
          args:
            - "--dummy-certificates"
            - "--no-auth"
            - "-nnats"
            - "--http=0.0.0.0:8081"
            - "--request-timeout=6s"
          ports:
          - containerPort: 8080
          - containerPort: 8081
      imagePullSecrets:
        - name: regcred
