[package]
name = "common-lib"
version = "0.1.0"
authors = ["paul <paul.yoong@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
strum = "0.21.0"
strum_macros = "0.21.1"
serde_json = "1.0.67"
percent-encoding = "2.1.0"
tracing = "0.1.26"
tokio = { version = "1.11.0", features = [ "full" ] }
snafu = "0.6.10"
etcd-client = "0.7.2"
serde = { version = "1.0.130", features = ["derive"] }
nats = "0.15.1"
structopt = "0.3.23"
log = "0.4.14"
env_logger = "0.9.0"
# Version is pinned due to incompatibilities with the instrument crate in the newer versions
# https://github.com/tokio-rs/tracing/issues/1219
async-trait = "0.1.51"
dyn-clonable = "0.9.0"
smol = "1.2.5"
once_cell = "1.8.0"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.20"
openapi = { path = "../openapi" }
parking_lot = "0.11.2"
async-nats = "0.10.1"

[dev-dependencies]
composer = { path = "../composer" }
oneshot = "0.1.2"
rpc = { path = "../rpc"}
